services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=taskpass123
      - POSTGRES_DB=taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
